### PR TITLE
Pytorch-GradCAM as a library

### PR DESCRIPTION
**Pull request by jdecid**
Having this tool with almost 2k stars, I think that it would be interesting to offer it as a PyPI library to allow developers and researchers to use it plug-and-play instead of having to manually download the code and tune it. 

In this pull request, I have just created the setup files, separated the main into a separate file for example, and moved the main code inside the library folder. 

It can be used in the same way by copy-pasting but now it is also possible to create and upload a library following these [steps](https://packaging.python.org/tutorials/packaging-projects/). You can see it [here](https://pypi.org/project/pytorch-grad-cam/).

### CODE REVIEW

**Comment by jacobgil** [comment]
Wow this is awesome, thanks a lot.

Do you think it makes sense that deprocess_image and show_cam_on_image will also be moved into the library as helper utilities?

**Comment by jdecid** [comment]
Yes, I did this first version as a little draft in general terms. If I have time I can try to refactor the code a bit to encapsulate the gradcam functionality itself and move the auxiliary/utility functions to another package or in the example code.

**Comment by jdecid** [comment]
I have changed and organized a few more things. Check it and merge it if you think that it's ok now!

**Comment by jacobgil** [comment]
Hi, thank you!
Sorry for the late response.
I am working on this (copied it into a new branch) - adding a bit and also trying to incorporate feedback from the issues like reversing the gradients.

**Comment by jacobgil** [comment]
Hi,
Here is the branch:
https://github.com/jacobgil/pytorch-grad-cam/tree/refactoring_for_pypi
I'm going to merge it into master soon.

I wanted to push to https://pypi.org/project/pytorch-grad-cam/ however I don't have access.
Can you please add me there?

**Comment by jacobgil** [comment]
Merged other PR that includes this, but also:
- GradCAM++
- Feedback from open issues like sorting gradients
- Works with all torchvision models
- A bit of simplification

**Pull request closed without merging**
