### PR TITLE
Example for Swin Transformer

### PR DESCRIPTION
**Pull request by AmbiTyga**
- Added a directory name usage_example
- Moved vit_example.py to usage_example
- changed `model.blocks[-2].norm1` to `model.blocks[-1].norm1` in usage_example/vit_example.py
- Added a new swinT_example.py to try out gradient mapping with Swin Tranformers
- Added a new section `Swin Transformer` in Readme.md with generated examples and method to use Swin Transformer with the library.
- Changed references formating

### CODE REVIEW

**Comment by jacobgil** [comment]
Hi, thanks!
Some comments:
- The dog category examples for the swin transformer don't look convincing
I think we should improve them first.
Is this with the smoothing? If yes, maybe try without?
Try an earlier block?
- Lets please keep the previous reference formatting

**Comment by AmbiTyga** [comment]
- I'll try it on with other blocks 
- Please tell me what is the ImageNet class index of that dog and the cat as shown in images, this can make it easier for me
- Is it possible to use other images for generating such examples?

**Comment by AmbiTyga** [comment]
| Category  | GradCAM  |  AblationCAM |  ScoreCAM |
| ---------|----------|------------|------------|
| Dog    | swinT_dog_gradcam_cam     |  swinT_dog_abaltioncam_cam  |swinT_dog_scorecam_cam  |
| Cat    | swinT_cat_gradcam_cam     |  swinT_cat_abaltioncam_cam   | swinT_cat_scorecam_cam   |

- I'm sorry, I checked and found that the previous maps were generated using ImagNet 22k with untrained Classifier head. 
These are the changes now
- I'll undo the references formatting

**Comment by jacobgil** [comment]
Thanks!
Another comment -
Looks like one of the Swin transformer dog images is from ViT
./examples/vit_cat_scorecam_cam.jpg

**Comment by AmbiTyga** [comment]
Changed that.

**Review by jacobgil — APPROVED** [review]

**Comment by jacobgil** [comment]
Super cool.
The Swin Transformer images are pretty convincing.
Thanks for your contribution!

**Pull request merged**
